# Generated by Django 5.2.8 on 2025-12-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_trashed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
