# Generated by Django 5.2.8 on 2025-11-25 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to='qr_master.qrcode')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
