# Generated by Django 5.2.8 on 2025-11-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_master', '0002_qrscanhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrscanhistory',
            name='device',
        ),
        migrations.AddField(
            model_name='qrscanhistory',
            name='device_summary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
