# Generated by Django 5.2.8 on 2025-11-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_master', '0003_remove_qrscanhistory_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
