# Generated by Django 5.2.8 on 2025-12-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw_converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='converted_file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='convert',
            field=models.CharField(choices=[('PDF-To-Word', 'PDF-To-Word'), ('Word-To_PDF', 'Word-To_PDF')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files/'),
        ),
        migrations.AddField(
            model_name='document',
            name='word',
            field=models.FileField(blank=True, null=True, upload_to='word_files/'),
        ),
    ]
