# Generated by Django 5.2.8 on 2025-12-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pw_converter', '0002_remove_document_converted_file_remove_document_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='convert',
        ),
    ]
